services:
  keycloak:
    build:
      context: ./keycloak
      dockerfile: Dockerfile
    container_name: keycloak
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://serverdb:5432/keycloakdb
      KC_DB_USERNAME: administrator
      KC_DB_PASSWORD: administrator
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8080
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_LOG_LEVEL: info
      KC_METRICS_ENABLED: true
      KC_HEALTH_ENABLED: true
      KEYCLOAK_ADMIN: administrator
      KEYCLOAK_ADMIN_PASSWORD: administrator
    ports:
      - '6003:8080'
      - '6011:9000'
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./keycloak/create-realm.sh:/opt/keycloak/create-realm.sh
      - ./keycloak/realm-config.json:/opt/keycloak/realm-config.json
    networks:
      - produto_network
    entrypoint: ["/opt/keycloak/wait-for-postgres.sh", "&&", "/opt/keycloak/create-realm.sh", "/opt/keycloak/realm-config.json"]
