version: '3.8'

services:
  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
      MINIO_SITE_REGION: ${MINIO_SITE_REGION}
      MINIO_SITE_NAME: ${MINIO_SITE_NAME}
      MINIO_BROWSER: ${MINIO_BROWSER}
      MINIO_DOMAIN: ${MINIO_DOMAIN}
      MINIO_PROMETHEUS_AUTH_TYPE: ${MINIO_PROMETHEUS_AUTH_TYPE}
    ports:
      - "6012:9000"
      - "6001:9001"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - produto_network

volumes:
  minio_data:

networks:
  produto_network:
    external: true
