version: '3.8'

services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=administrator
      - N8N_BASIC_AUTH_PASSWORD=administrator
    networks:
      - produto_network

volumes:
  n8n_data:

networks:
  produto_network:
    external: true
