version: '3.8'

services:
  redash:
    image: redash/redash:latest
    container_name: redash
    depends_on:
      - postgres
      - redis
    environment:
      REDASH_DATABASE_URL: postgresql+psycopg2://administrator:administrator@serverdb:5432/redash
      REDASH_REDIS_URL: redis://redis:6379/0
    ports:
      - "5000:5000"
    networks:
      - produto_network

networks:
  produto_network:
    external: true
