version: '3.8'

services:
  spark-master:
    image: bitnami/spark:3.4.1-debian-11-r1
    container_name: spark-master
    environment:
      - SPARK_MODE=master
    ports:
      - "8080:8080"
      - "7077:7077"
    networks:
      - produto_network

  spark-worker:
    image: bitnami/spark:3.4.1-debian-11-r1
    container_name: spark-worker
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    depends_on:
      - spark-master
    networks:
      - produto_network

networks:
  produto_network:
    external: true
